name: lint

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the project
              uses: actions/checkout@v2

            - name: Install Node & Yarn
              uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version: "14"

            - name: Install the packages
              run: yarn install

            - name: Check the formatting
              run: yarn run chk
