name: test

on: push

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the project
              uses: actions/checkout@v2
            - name: Install Node & Yarn
              uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version: "14"
            - name: Install the packages
              run: yarn install
            - name: Run the E2E tests
              run: yarn run test:e2e:once
            - name: Verify the coverage
              run: yarn run verify:coverage:for-e2e
    unit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the project
              uses: actions/checkout@v2
            - name: Install Node & Yarn
              uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version: "14"
            - name: Install the packages
              run: yarn install
            - name: Run the unit tests
              run: yarn run test:unit:once
            - name: Verify the coverage
              run: yarn run verify:coverage:for-unit
